# Generated by Django 6.1 on 2026-08-22 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('minimum_priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Standard'), (3, 'High'), (4, 'Emergency')], default=1)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_space', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='maintenance.bedspace')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('water_active', models.BooleanField(default=False)),
                ('cannot_secure', models.BooleanField(default=False)),
                ('electrical_hazard', models.BooleanField(default=False)),
                ('room_unusable', models.BooleanField(default=False)),
                ('derived_priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Standard'), (3, 'High'), (4, 'Emergency')])),
                ('current_priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Standard'), (3, 'High'), (4, 'Emergency')])),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('bed_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='maintenance.bedspace')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='maintenance.category')),
                ('common_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='maintenance.commonarea')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-current_priority', 'created_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bed_space__isnull', False), ('common_area__isnull', True)), models.Q(('bed_space__isnull', True), ('common_area__isnull', False)), _connector='OR'), name='report_has_exactly_one_location')],
            },
        ),
    ]
