# Generated by Django 6.1 on 2026-08-22 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_category_studentprofile_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('comment', 'Comment'), ('status_change', 'Status change'), ('priority_change', 'Priority change'), ('escalation', 'Escalation')], max_length=20)),
                ('body', models.TextField(blank=True)),
                ('from_value', models.CharField(blank=True, max_length=30)),
                ('to_value', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_events', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='maintenance.report')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Corroboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corroborations', to='maintenance.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corroborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('report', 'student')},
            },
        ),
    ]
